services:
  quote-engine:
    build: .
    restart: unless-stopped

    expose:
      - "5000"

    environment:
      FLASK_ENV: production
      FLASK_DEBUG: "False"
      PRUSA_SLICER_PATH: /usr/bin/prusa-slicer
      SECRET_KEY: ${SECRET_KEY}

    volumes:
      - ./config.json:/app/config.json
      - ./logs:/app/logs

    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
